import os
import shutil
from autogal.agents.base import BaseAgent
from autogal.core.domain.scenario import Scenario

class CoderAgent(BaseAgent):
    """
    编码 Agent：负责将结构化的 Scenario 对象转化为 Ren'Py 源代码 (.rpy)
    并组装成完整的项目文件夹。
    """

    async def execute(self, scenario: Scenario, template_path: str, output_path: str):
        print(f"⚙️ [CoderAgent] 正在构建项目：{output_path}...")

        # 1. 准备项目目录
        if os.path.exists(output_path):
            shutil.rmtree(output_path)
        shutil.copytree(template_path, output_path)

        # 2. 生成 script.rpy 内容
        script_content = self._generate_rpy_content(scenario)

        # 3. 写入文件
        rpy_file_path = os.path.join(output_path, "game", "script.rpy")
        with open(rpy_file_path, "w", encoding="utf-8") as f:
            f.write(script_content)

        print(f"✅ [CoderAgent] Ren'Py 脚本构建完成！")

    def _generate_rpy_content(self, scenario: Scenario) -> str:
        """将 Scenario 对象翻译为 Ren'Py DSL 字符串"""
        lines = [f"# Generated by AutoGal Agent\n# Title: {scenario.title}\n"]

        # --- A. 定义角色 ---
        for char in scenario.characters:
            line = f'define {char.var_name} = Character("{char.name}", color="{char.color}")'
            lines.append(line)

        lines.append("\n# --- 游戏开始 ---")
        lines.append("label start:")

        # 跟踪当前显示的角色
        shown_characters = set()

        # --- B. 遍历场景 ---
        for scene in scenario.scenes:
            lines.append(f"\n    # Scene: {scene.scene_id}")
            # 展现背景图
            lines.append(f"    scene bg_{scene.scene_id}")
            # 新场景重置显示的角色
            shown_characters.clear()

            for dia in scene.dialogues:
                # 转义特殊字符：Ren'Py 中 % 需要写成 %%
                text = dia.text.replace("%", "%%")

                if dia.speaker_var:
                    # 如果这个角色还没显示，先显示立绘
                    if dia.speaker_var not in shown_characters:
                        lines.append(f"    show char_{dia.speaker_var} at center")
                        shown_characters.add(dia.speaker_var)
                    lines.append(f'    {dia.speaker_var} "{text}"')
                else:
                    # 旁白
                    lines.append(f'    "{text}"')

        lines.append("\n    return")
        return "\n".join(lines)
    
'''
模板复用 (shutil.copytree)：Ren'Py 游戏不仅有代码，
还有很多 gui.rpy、options.rpy 等 UI 配置文件。
我们直接复制一个标准模板，只修改最核心的 script.rpy。

DSL 翻译：你注意到 _generate_rpy_content 里的缩进（4个空格）了吗？
Ren'Py 像 Python 一样严格依赖缩进。Agent 必须精确控制每一行的前缀空间。

资产联动：这里使用了 scene bg_{scene.scene_id}，这必须和 ArtistAgent 
保存图片时的命名规则完全一致，否则 Ren'Py 运行时会报错“找不到图片”。
'''